import os

DATA_PATH_WANTED = "./data/wanted"
DATA_W_PATH = "./data/integration"
fields = ["id", "카테고리", "주요업무", "자격요건", "우대사항", "복리후생", "제목", "기업명", "지역", "산업", "근무형태", "경력", "학력", "급여", "키워드"]

category = []
major_task = []
qualification = []
prefer_treatment = []
benefit = []
title = []
company = []
location = []
industry = []
job_type = []
career = []
education = []
salary = []
keyword = []
category_mapping = {
    '서비스 기획자': 0,
    'Service Planner': 0,
    '사업개발·기획자': 0,
    'Business Development': 0,
    '전략 기획자': 0,
    'Strategic Planner': 0,
    '경영지원': 0,
    'Business Support Manager': 0,
    '해외 사업개발·기획자': 0,
    'Global Business Development Manager': 0,
    '조직관리': 0,
    'Organization Management': 0,
    '리스크 관리 전문가': 0,
    'Risk Management Specialist': 0,
    '경영 혁신가': 0,
    'Management Innovator': 0,
    '지역 관리 매니저': 0,
    'Local Manager': 0,
    'CO': 0,
    'hief Operation Officer': 0,
    'CS': 0,
    'hief Strategy Officer': 0,
    '애자일코치': 0,
    'Agile Coach': 0,
    '전시 기획자': '0',
    'Exhibition Planner': 0,
    '지점장': 0,
    'Branch Manager': 0,
    '조직문화': 0,
    '데이터 분석가': 1,
    'Data Analyst': 1,
    '구매담당': 1,
    'Purchasing Manager': 1,
    '디지털 마케터': 1,
    'Digital Marketer': 1,
    '마케터': 1,
    'Marketer': 1,
    '콘텐츠 마케터': 1,
    'Content Marketer': 1,
    '퍼포먼스 마케터': 1,
    'Performance Marketer': 1,
    'Performance Marketing Manager': 1,
    '마케팅 전략 기획자': 1,
    'Marketing Strategy Planner': 1,
    '브랜드 마케터': 1,
    'Brand Marketer': 1,
    '소셜 마케터': 1,
    'Social Marketer': 1,
    '글로벌 마케팅': 1,
    'Global Marketing Mgr.': 1,
    '그로스 해커': 1,
    'Growth Hacker': 1,
    '모바일마케팅': 1,
    'Mobile Marketing Specialist': 1,
    'PR 전문가': 1,
    'PR Specialist': 1,
    '마케팅 디렉터': 1,
    'Marketing Director': 1,
    '마켓 리서처': 1,
    'Market Researcher': 1,
    '제휴': 1,
    'Partnership Specialist': 1,
    'CM': 1,
    'hief Marketing Officer': 1,
    'ATL 마케터': 1,
    'ATL Marketer': 1,
    'BTL 마케터': 1,
    'BTL Marketer': 1,
    'CB': 1,
    'hief Brand Officer': 1,
    'Sports 전문가': 1,
    'Sports Specialist': 1,
    'CRM 전문가': 1,
    'CRM Specialist': 1,
    '회계·경리': 3,
    'Accountant': 3,
    '급여담당': 3,
    'Salar': 3,
    'Compensation': 3,
    '자금담당': 4,
    'Finance Manager': 4,
    'CF': 4,
    'hief Financial Officer': 4,
    '재무 담당자': 4,
    'IR': 4,
    '내부통제 담당자': 4,
    'Auditor': 4,
    '총무': 5,
    'General Affairs': 5,
    '법무담당': 5,
    'Legal Representative': 5,
    '비서': 6,
    'Secretary': 6,
    '오피스 관리': 7,
    'Office Manager': 7,
    '인사담당': 7,
    'HR Manager': 7,
    '리크루터': 7,
    'Recruiter': 7,
    '평가·보상': 7,
    'Performance Evaluation': 7,
    'HRBP': 7,
    'HR Business Partner': 7,
    '노무·노사': 7,
    'Labor and Management': 7,
    'HRD': 7,
    'HR Developmen': 7,
    'Training': 7,
    '기술 교육': 7,
    'Technology Educator': 7,
    'E-러닝': 7,
    'E-Learning': 7,
    '사내 강사': 7,
    'Lecturer': 7,
    '교사': 7,
    'Teacher': 7,
    '사무보조': 8,
    'Admin Assistant': 8,
    'Administrative Assistant': 8,
    '세미나/포럼 기획자': 9,
    'Event Producer': 9,
    '리셉션': 9,
    'Receptionist': 9,
    '기업영업': 10,
    'Enterprise Sales': 10,
    '외부영업': 10,
    'Sales Specialist': 10,
    '내부영업': 10,
    'Inside Sales Specialist': 10,
    '의료기기 영업': 10,
    'Medical Device Sales Specialist': 10,
    '제약영업': 10,
    'Pharmaceutical Sales Specialist': 10,
    '영업 관리자': 11,
    'Sales Team Lead': 11,
    '주요고객사 담당자': 11,
    'Account Manager': 11,
    '고객성공매니저': 11,
    'Customer Success Manager': 11,
    '기술영업': 12,
    'Technical Sales Specialist': 12,
    '세일즈 엔지니어': 12,
    'Sales Engineer': 12,
    '기술지원': 12,
    'Technical Support': 12,
    '사업수주 엔지니어': 12,
    '솔루션 컨설턴트': 13,
    'Solutions Consultant': 13,
    '미디어 세일즈': 14,
    'Media Sales Manager': 14,
    '자산운용가': 15,
    'Asset Manager': 15,
    '자산관리사': 15,
    'Financial Advisor': 15,
    '보험 에이전트': 15,
    '매장 관리자': 16,
    'Store Manager': 16,
    '매장점원': 16,
    'Retail Salesperson': 16,
    '플로리스트': 16,
    '아웃바운드 텔레마케터': 17,
    'Outbound Telemarketer': 17,
    '인바운드 텔레마케터': 18,
    'Inbound Telemarketer': 18,
    'CS 매니저': 19,
    'Customer Service Manager': 19,
    '서비스 운영': 19,
    'Customer Service Representative': 19,
    'CS 어드바이저': 19,
    'CS Advisor': 19,
    '웹 개발자': 21,
    'Web Developer': 21,
    '프론트엔드 개발자': 21,
    'Front-end Engineer': 21,
    'Node.js 개발자': 21,
    'Node.js Developer': 21,
    'PHP 개발자': 21,
    'PHP Developer': 21,
    '자바 개발자': 22,
    'Java Developer': 22,
    '안드로이드 개발자': 22,
    'Android Developer': 22,
    'iOS 개발자': 22,
    'iOS Developer': 22,
    '파이썬 개발자': 22,
    'Python Developer': 22,
    '++ 개발자': 22,
    '++ Developer': 22,
    '블록체인 플랫폼 엔지니어': 22,
    'Blockchain Platform Engineer': 22,
    '.NET 개발자': 22,
    '.NET Developer': 22,
    '임베디드 개발자': 22,
    'Embedded Developer': 22,
    '크로스플랫폼 앱 개발자': 22,
    'Cross-platform App Developer': 22,
    '루비온레일즈 개발자': 22,
    'Ruby on Rails Developer': 22,
    'VR 엔지니어': 22,
    'VR Engineer': 22,
    'DevOps / 시스템 관리자': 23,
    'DevOps / System Admin': 23,
    '서버 개발자': 24,
    'Back-end Engineer': 24,
    '시스': 24,
    '트워크 관리자': 24,
    'Syste': 24,
    'Network Administrator': 24,
    '보안 엔지니어': 24,
    'Security Engineer': 24,
    'I&C 엔지니어': 24,
    '웹 퍼블리셔': 27,
    'Web Publisher': 27,
    'UX 디자이너': 28,
    'UX Designer': 28,
    'U': 28,
    'UI 디자이너': 28,
    'UI Designer': 28,
    '웹 디자이너': 28,
    'Web Designer': 28,
    '모바일 디자이너': 28,
    'Mobile Designer': 28,
    '소프트웨어 엔지니어': 29,
    'Software Engineer': 29,
    '하드웨어 엔지니어': 29,
    'Hardware Engineer': 29,
    '지리정보시스템': 30,
    'PM·PO': 31,
    'Project Manager': 31,
    'Q': 32,
    '스트 엔지니어': 32,
    'Test Engineer': 32,
    '운영 매니저': 33,
    'Operations Manager': 33,
    '개발 매니저': 33,
    'Development Manager': 33,
    '프로덕트 매니저': 33,
    'Product Manager': 33,
    '콘텐츠 크리에이터': 33,
    'Content Creator': 33,
    '게임 기획자': 34,
    'Game Planner': 34,
    '게임 그래픽 디자이너': 34,
    'Game Graphic Designer': 34,
    '게임 아티스트': 34,
    'Game Artist': 34,
    '게임 클라이언트 개발자': 34,
    'Game Client Developer': 34,
    '모바일 게임 개발자': 34,
    'Mobile Game Developer': 34,
    '유니티 개발자': 34,
    'Unity Developer': 34,
    '게임 서버 개발자': 34,
    'Game Server Developer': 34,
    '언리얼 개발자': 34,
    'Unreal Developer': 34,
    '게임운영자(GM)': 34,
    'Game Master': 34,
    '영': 36,
    '성 엔지니어': 36,
    'Vide': 36,
    'Voice Engineer': 36,
    '션 디자이너': 36,
    'Motion Designer': 36,
    '영상 편집가': 36,
    'Video Editing Specialist': 36,
    '에디터': 36,
    'Editor': 36,
    '데이터 엔지니어': 37,
    'Data Engineer': 37,
    '머신러닝 엔지니어': 37,
    'Machine Learning Engineer': 37,
    '데이터 사이언티스트': 37,
    'Data Scientist': 37,
    '빅데이터 엔지니어': 37,
    'Big Data Engineer': 37,
    'CI': 37,
    'hief Information Officer': 37,
    '정보 분석가': 37,
    'BI 엔지니어': 38,
    'BI Engineer': 38,
    '그래픽스 엔지니어': 38,
    'Graphics Engineer': 38,
    '그래픽 디자이너': 38,
    'Graphic Designer': 38,
    'BI/BX 디자이너': 38,
    'BI/BX Designer': 38,
    '3D 디자이너': 38,
    '3D Designer': 38,
    '일러스트레이터': 38,
    'Illustrator': 38,
    '출': 39,
    '편집 디자이너': 39,
    'Editorial Designer': 39,
    '제품 디자이너': 40,
    'Product Designer': 40,
    '패키지 디자이너': 40,
    'Packaging Designer': 40,
    '산업 디자이너': 40,
    'Industrial Designer': 40,
    '가구 디자이너': 40,
    'Furniture Designer': 40,
    '2D 디자이너': 41,
    '2D Designer': 41,
    '캐릭터 디자이너': 41,
    'Character Designer': 41,
    '패션 디자이너': 42,
    'Fashion Designer': 42,
    '패브릭 디자이너': 42,
    'Textile Designer': 42,
    'VMD': 42,
    'VMD Designer': 42,
    '인테리어 디자이너': 43,
    'Interior Designer': 43,
    '공간 디자이너': 43,
    'Space Designer': 43,
    '전시 디자이너': 43,
    'Exhibition Designer': 43,
    '조경 디자이너': 43,
    '광고 디자이너': 44,
    'Ad Designer': 44,
    '아트 디렉터': 44,
    'Art Director': 44,
    '이벤트 기획자': 46,
    'Event Planner': 46,
    '안내원': 47,
    '보안요원': 48,
    '경호원': 48,
    'AS 기술자': 50,
    'Service Technician': 50,
    '정비공': 50,
    'Mechanic': 50,
    '외식업 종사자': 51,
    'Restaurant Worker': 51,
    '바텐더': 51,
    '레스토랑 관리자': 51,
    'Restaurant Manager': 51,
    '바리스타': 51,
    '소믈리에': 51,
    '여행 에이전트': 53,
    'Travel Agent': 53,
    '승무원': 53,
    '헬스케어매니저': 54,
    'Healthcare Manager': 54,
    '피부관리사': 55,
    '헤어 디자이너': 55,
    '미용사': 55,
    '애견 미용사': 55,
    '요리사': 56,
    'Chef': 56,
    '푸드스타일리스트': 56,
    'Food Stylist': 56,
    '영양사': 56,
    'Nutritionist': 56,
    '제과·제빵사': 56,
    'Baker': 56,
    '컨설턴트': 58,
    'Consultant': 58,
    'HR 컨설턴트': 58,
    'HR Consultant': 58,
    '부동산 자산 관리자': 58,
    'Property Manager': 58,
    '금융공학자': 58,
    'Financial Engineer': 58,
    '투자·증권': 59,
    'Investmen': 59,
    'Stock Manager': 59,
    '애널리스트': 59,
    'Analyst': 59,
    '트레이더': 59,
    'Trader': 59,
    '투자은행가': 59,
    'Investment Banker': 59,
    '헤드헌터': 61,
    'Headhunter': 61,
    '통·번역': 62,
    'Translator': 62,
    '변호사': 63,
    'Lawyer': 63,
    '법무 자문위원': 63,
    'General Counsel': 63,
    '법무사': 63,
    'Judicial Scrivener': 63,
    '특허담당': 63,
    'Patent Administrator': 63,
    '수사관': 63,
    '법무관': 63,
    '변리사': 63,
    '준법감시인': 63,
    'Compliance Manager': 63,
    '회계담당': 64,
    'Accountan': 64,
    'Treasurer': 64,
    '재무 분석가': 64,
    'Financial Analyst': 64,
    '공인회계사': 64,
    'CPA': 64,
    '세무사': 64,
    'Tax Accountant': 64,
    '손해 사정관': 65,
    'Damage Appraiser': 65,
    '계리사': 65,
    'Actuary': 65,
    '언더라이터': 65,
    'Underwriter': 65,
    'CT': 67,
    'hief Technology Officer': 67,
    '메뉴개발': 67,
    'Restaurant Management': 67,
    '연구원': 67,
    'Researcher': 67,
    '생명공학 연구원': 67,
    'Biotechnology Researcher': 67,
    '약학 분석 화학자': 67,
    'Pharmaceutical Analytical Chemist': 67,
    '임상시험 연구원': 67,
    'Clinical Trial Researcher': 67,
    '로봇·자동화': 67,
    'Robot·AI': 67,
    '항공우주 공학자': 67,
    'Aerospace Engineer': 67,
    '건설 엔지니어': 67,
    'Construction Engineer': 67,
    '광산 기술자': 67,
    '원자력·에너지': 67,
    'Nuclear Engineer': 67,
    'CE': 68,
    'hief Executive Officer': 68,
    '큐레이터': 69,
    'Curator': 69,
    '지리학자': 70,
    '의사': 71,
    'Doctor': 71,
    '치과의사': 71,
    '한의사': 71,
    'Oriental Medical Doctor': 71,
    '수의사': 72,
    'Veterinarian': 72,
    '수의 테크니션': 72,
    'Veterinary Specialist': 72,
    '약사': 73,
    'Pharmacist': 73,
    '약사 보조원': 73,
    '임상시험 간호사': 74,
    'Clinical Trial Nurse': 74,
    '간호사': 74,
    'Nurse': 74,
    '조무사': 75,
    '간호 조무사': 75,
    '임상병리사': 76,
    'Medical Technologist': 76,
    '임상심리사': 76,
    '치과위생사': 76,
    '작업 치료사': 76,
    '물리 치료사': 76,
    '호흡장애 치료사': 76,
    '검안사': 76,
    '연구실 기사': 76,
    '방사선사': 76,
    '의무 기록사': 76,
    '인명 구조원': 76,
    '응급구조사': 76,
    '병원 코디네이터': 77,
    '청구 담당자': 78,
    'Claims Manager': 78,
    '증례 관리자': 79,
    '간병인': 79,
    '생산공학 엔지니어': 80,
    'Production Engineer': 80,
    '생산직 종사자': 80,
    'Production Worker': 80,
    '제조 엔지니어': 80,
    'Manufacturing Engineer': 80,
    '제조 테스트 엔지니어': 80,
    'Manufacturing Test Engineer': 80,
    '조립 기술자': 80,
    'Assembly Technician': 80,
    'QA 엔지니어': 81,
    'QA Engineer': 81,
    'QC 엔지니어': 81,
    'QC Engineer': 81,
    '품질 관리자': 81,
    'Quality Manager': 81,
    '생산 관리자': 81,
    'Production Manager': 81,
    '공정 관리자': 81,
    'Process Manager': 81,
    '자재관리·구매': 81,
    'Materials Manager': 81,
    '기계 엔지니어': 82,
    'Mechanical Engineer': 82,
    '설비 엔지니어': 82,
    'Equipment Engineer': 82,
    '장비 엔지니어': 82,
    '프로젝트 엔지니어': 82,
    'Project Engineer': 82,
    '회전기계 엔지니어': 82,
    'Rotary Machine Engineer': 82,
    '선박 공학자': 82,
    '기계·설비·설계': 82,
    'Machiner': 82,
    'Equipment Operation': 82,
    '기계제작 기술자': 82,
    'Mechanical Production technician': 82,
    '재료공학자': 83,
    'Materials Engineer': 83,
    '금속 공학자': 83,
    '용접기사': 83,
    'Welder': 83,
    '세라믹 엔지니어': 84,
    '전자 엔지니어': 85,
    'Electronics Engineer': 85,
    '전기기계 공학자': 85,
    'Electro Mechanical Engineer': 85,
    '전기 엔지니어': 85,
    'Electrical Engineer': 85,
    '제어 엔지니어': 85,
    'Control Engineer': 85,
    '공정 엔지니어': 85,
    'Process Engineer': 85,
    'RF 엔지니어': 85,
    'RT Engineer': 85,
    '시운전 엔지니어': 85,
    '전자계전 엔지니어': 85,
    '제품 엔지니어': 86,
    'Product Engineer': 86,
    '반도체·디스플레이': 86,
    'Semiconductor · Screens': 86,
    '화학공학 엔지니어': 87,
    'Chemical Engineer': 87,
    '석유공학 엔지니어': 87,
    '유전 공학자': 87,
    '시추 엔지니어': 87,
    '플라스틱 엔지니어': 87,
    '화학자': 87,
    'Chemist': 87,
    '섬유·의류·패션': 88,
    'Textile · Clothing · Fashion': 88,
    '식품가공·개발': 89,
    'Food Processing · Development': 89,
    '유전공학자': 89,
    'Geneticist': 89,
    '미생물학자': 89,
    'Microbiologist': 89,
    '농업 공학자': 89,
    'Agricultural Engineer': 89,
    '생물의학자': 89,
    'Biological Scientist': 89,
    '자동차 공학자': 90,
    'Automotive Engineer': 90,
    'CAD·3D 설계자': 90,
    'CAD·3D Engineer': 90,
    '도면 담당자': 90,
    'Drafter': 90,
    '도면 작성가': 90,
    'Floor Plan Creator': 90,
    '인허가 담당 엔지니어': 91,
    'Licensing Engineer': 91,
    '토목기사': 92,
    'Civil Engineer': 92,
    '구조공학 엔지니어': 92,
    'Structural Engineer': 92,
    '지질공학자': 92,
    '측량·계측': 92,
    '실내건축': 93,
    'Interior Architecture': 93,
    '목수': 93,
    'Carpenter': 93,
    '건축가': 93,
    'Architect': 93,
    '소방안전 기술자': 94,
    '배관설계 엔지니어': 94,
    'Pipe Design Engineer': 94,
    '보일러 엔지니어': 94,
    '고압설계 엔지니어': 94,
    '전기 기술자': 94,
    'Electrician': 94,
    '배관공': 94,
    '연관공': 94,
    '환경 엔지니어': 95,
    '환경 안전기사': 95,
    '플랜트 엔지니어': 95,
    '저수처리 엔지니어': 95,
    '터빈 공학자': 95,
    '플랜트 관리자': 95,
    '환경 전문가': 95,
    '건축시공·감리': 96,
    'Construction Manager': 96,
    '현장 소장': 96,
    'Site Manager': 96,
    '인스톨러': 96,
    '페인터': 96,
    '산업 엔지니어': 97,
    'Industrial Engineer': 97,
    '보건안전 엔지니어': 97,
    'Health and Safety Engineer': 97,
    '광산 안전 기술자': 97,
    '안전 관리자': 97,
    'Safety Manager': 97,
    '유지보수 관리자': 97,
    'Maintenance Manager': 97,
    '건설 안전·품질·검사': 97,
    'Construction Inspector': 97,
    '감정평가사': 98,
    'Appraiser': 98,
    '부동산 중개사': 98,
    'Realtor': 98,
    '견적 기술자': 98,
    'Estimation Engineer': 98,
    '관리인': 99,
    'Manager': 99,
    '해양공학자': 100,
    'Marine Engineer': 100,
    '물류담당': 100,
    'Logistics Manager': 100,
    '입·출고 관리자': 100,
    'Import/Export Specialist': 100,
    '물류 분석가': 100,
    'Logistics Analyst': 100,
    '유통 관리자': 100,
    'Distribution Manager': 100,
    '운송 관리자': 100,
    'Transportation Manager': 100,
    '항공 운송': 100,
    'Air Transportation Specialist': 100,
    '해운·해양 운송': 100,
    'Marine Transportation Specialist': 100,
    '보세사': 100,
    '해외영업': 101,
    'International Sales Mgr.': 101,
    '바이어관리·상담·개발': 101,
    'Supply Chain Manager': 101,
    '웨어하우스': 102,
    'Warehouse Specialist': 102,
    '배송담당': 103,
    'Shippin': 103,
    'Receiving Clerk': 103,
    'MD': 104,
    'Merchandiser': 104,
    '리테일 MD': 104,
    'Retail Merchandiser': 104,
    '패션 MD': 104,
    'Fashion Merchandiser': 104,
    '가맹점 관리자': 104,
    'Franchise Manager': 104,
    '비주얼머천다이저': 104,
    'Visual Merchandiser': 104,
    '식품 MD': 104,
    'Food MD': 104,
    '수출입사무': 105,
    'Logistics Coordinator': 105,
    '무역사무': 105,
    'Trade administration': 105,
    '선': 105,
    '송 사무원': 105,
    'Shipmen': 105,
    'Mailing Clerk': 105,
    '관세사': 105,
    'Logistics Customs Officer': 105,
    '원산지 관리사': 105,
    '운행 관리원': 106,
    'Dispatcher': 106,
    '운전기사': 106,
    'Driver': 106,
    '지게차 운전사': 107,
    'Forklift Driver': 107,
    '디젤 정비공': 107,
    '화물트럭 운전기사': 107,
    'Cargo Truck Drivers': 107,
    '중장비 기술자': 107,
    'PD': 108,
    'Producer': 108,
    '비디오 제작': 108,
    'Video Production': 108,
    '리포터': 110,
    'Reporter': 110,
    '작가': 111,
    'Writer': 111,
    '저널리스트': 112,
    'Journalist': 112,
    '공연 기획자': 114,
    'Stage Producer': 114,
    '광고 기획자(AE)': 116,
    'Account Executive': 116,
    '카피라이터': 116,
    'Copywriter': 116,
    '키워드광고': 116,
    'SEO Marketing Manager': 116,
    '라이센스 관리자': 116,
    'Licence Manager': 116,
    '음향 엔지니어': 117,
    'Sound Engineer': 117,
    '출판 기획자': 118,
    'Book Publisher': 118,
    '사진작가': 119,
    'Photographer': 119,
    '유치원·보육교사': 120,
    'Kindergarten and Childcare Teacher': 120,
    '초·중·고 교사': 121,
    '학원강사': 122,
    'Private Tutor': 122,
    '외국어교육': 123,
    'Foreign Language Educator': 123,
    '전문강사': 125,
    'Educational Instructor': 125,
    '자격증·기술전문교육': 125,
    'Certification and Technical Training': 125,
    '교수': 126,
    '교직원': 126,
    '교재·교육기획': 127,
    'Educational Publisher': 127,
    '경찰관': 129,
    '공무원': 129,
    '소방관': 129,
    '직업군인': 130,
    '사내 심리상담가': 134,
    'EAP Counselor': 134,
    '보호 관찰관': 134,
    '카운슬러': 134,
    '지역 전문가': 134,
    '자원봉사자': 134,
    '사회 복지사': 134,
    '요양 보호사': 134
}


with open(os.path.join(DATA_PATH_WANTED, "wanted.txt"), 'rt', encoding='UTF8') as f:
    for line in f.readlines():
        if line.startswith('id'):
            pass
        else:
            line = line.split('\t')

            cat = line[1]
            cat = cat.strip().split('//')
            cate = []
            for c in cat:
                c = c.strip()
                count = category_mapping.get(c, 'null')
                cate.append(count)
            category.append(' '.join(map(str, cate)))
            major_task.append(line[2])
            qualification.append(line[3])
            prefer_treatment.append(line[4])
            benefit.append(line[5])
            title.append(line[6])
            company.append(line[7])
            location.append(line[8])
            industry.append(line[9])
            job_type.append(line[10])
            career.append(line[11])
            education.append(line[12])
            salary.append(line[13])
            keyword.append(line[14])

f = open(os.path.join(DATA_W_PATH, "data_key15_wanted(category_numbering).txt"), 'w', encoding='UTF8')
for i in range(len(category) + 1):
    if i == 0:
        f.write('id\t카테고리\t주요업무\t자격요건\t우대사항\t복리후생\t제목\t기업명\t지역\t산업\t근무형태\t경력\t학력\t급여\t키워드\n')
    else:
        f.write(
            f'{i - 1}\t{category[i - 1]}\t{major_task[i - 1]}\t{qualification[i - 1]}\t{prefer_treatment[i - 1]}\t{benefit[i - 1]}\t'
            f'{title[i - 1]}\t{company[i - 1]}\t{location[i - 1]}\t{industry[i - 1]}\t{job_type[i - 1]}\t{career[i - 1]}\t{education[i - 1]}\t'
            f'{salary[i - 1]}\t{keyword[i - 1]}')
